import Head from 'next/head'
import { useEffect } from 'react';
// styles
import hero from "@/next-app/styles/sections/HomePage/Hero.module.scss";
// components
import MainLayout from '../components/MainLayout';
import Hero from '../sections/HomePage/Hero';
import About from "../sections/HomePage/About";
import Gallery from '../sections/HomePage/Gallery';
import Blogs from '../sections/HomePage/RecentPosts';


export const getServerSideProps = async () => {
  const resp = await fetch(`${process.env.LOCAL_API}/posts`);
  const data = await resp.json();
  return {
    props: {
      posts: data
    }
  }
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title> Its_d1a's Blog 💙 </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>

        <section className={hero.mainHero}>
          <Hero />
        </section>
        <section id='About_me'>
          <About />
        </section>
        <section>
          <Gallery />
        </section>
        <section>
          <Blogs data={posts} />
        </section>
      </MainLayout>
    </>
  )
}