import Head from 'next/head'
import Image from 'next/image';
// styles
import sassDefs from "@/next-app/styles/sassDef-s.module.scss";
// components
import Header from "@/next-app/components/Header";
import Hero from '../components/Hero';
// 

export default function Home() {
  return (
    <>
      <Head>
        <title>Отдуши устоз </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className='p-5'>
        <header className='w-full'>
          <Header />
        </header>
        <section className=''>
           <Hero />
        </section>
      </main>
    </>
  )
}
