export const images = [
    `/img/img (23).jpg`,
    `/img/img (2).jpg`,
    `/img/img (3).jpg`,
    `/img/img (4).jpg`,
    `/img/img (5).jpg`,
    `/img/img (6).jpg`,
    `/img/img (7).jpg`,
    `/img/img (8).jpg`,
    `/img/img (9).jpg`,
    `/img/img (10).jpg`,
    `/img/img (11).jpg`,
    `/img/img (19).jpg`,
    `/img/img (12).jpg`,
    `/img/img (13).jpg`,
    `/img/img (14).jpg`,
    `/img/img (15).jpg`,
    `/img/img (16).jpg`,
    `/img/img (17).jpg`,
    `/img/img (18).jpg`,
]